on: [push]
jobs: 
  Lint-Test-Build-Application: 
    name: Lint & Run Jest
    runs-on: self-hosted 
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: 📦 Install Dependencies 
        run: | 
          npm install eslint 
          npm install jest
      - name: 🧪 Lint Code 
        run: npm eslint 
      - name: 💉 Test Code
        run: npm jest
      - name: 📦 Build Application
        run: npm build
